// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIsGDgY34R7gOi4BtU0Me6RofcSWidMBY',
    appId: '1:1029046575523:web:7f4177937f2e8035f5ba16',
    messagingSenderId: '1029046575523',
    projectId: 'flutter-chat-app-9d4c0',
    authDomain: 'flutter-chat-app-9d4c0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9d4c0.firebasestorage.app',
    measurementId: 'G-D9Y5JZZ73D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQTcp7A1bwzHKCQPbBsz8HIIth3oxXFY',
    appId: '1:1029046575523:android:f8e7ee92f86a8a14f5ba16',
    messagingSenderId: '1029046575523',
    projectId: 'flutter-chat-app-9d4c0',
    storageBucket: 'flutter-chat-app-9d4c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-9bP3veiMyW1Yxt2mE8KpVo9-QZPDJMI',
    appId: '1:1029046575523:ios:e4997fe8b69c1274f5ba16',
    messagingSenderId: '1029046575523',
    projectId: 'flutter-chat-app-9d4c0',
    storageBucket: 'flutter-chat-app-9d4c0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-9bP3veiMyW1Yxt2mE8KpVo9-QZPDJMI',
    appId: '1:1029046575523:ios:e4997fe8b69c1274f5ba16',
    messagingSenderId: '1029046575523',
    projectId: 'flutter-chat-app-9d4c0',
    storageBucket: 'flutter-chat-app-9d4c0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIsGDgY34R7gOi4BtU0Me6RofcSWidMBY',
    appId: '1:1029046575523:web:ec82bc44d95cdcf5f5ba16',
    messagingSenderId: '1029046575523',
    projectId: 'flutter-chat-app-9d4c0',
    authDomain: 'flutter-chat-app-9d4c0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9d4c0.firebasestorage.app',
    measurementId: 'G-2SP7EKR22G',
  );
}
